name: Build and publish JVM-based images
on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  build_jvm_docker_image:
    name: Build and publish the JVM-based Docker image
    runs-on: ubuntu-24.04
    env:
      DOCKER_IMAGE_NAME: '${{ github.repository_owner }}/jhipster-lite'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ${{ env.DOCKER_IMAGE_NAME }}

      - name: Login to Docker Registry
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        uses: docker/login-action@v3.4.0
        id: login-hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the JVM-based Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
